name: Deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: |
          npm ci
          npm run build
      - uses: actions/checkout@v3
        with:
          ref: pages
          clean: false
      - run: |
          git add *.xml
      - run: |
          git config user.name "Yoshihiro Tanaka"
          git config user.email "contact@cordea.jp"
          git commit -m "update"
          git push
